const PLACEHOLDER_VIDEO_URL = "VIDEO_URL_AQUI";
const PLACEHOLDER_EMBED_URL = "YOUTUBE_EMBED_URL_AQUI";

const slugify = (value) =>
  String(value)
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const SUBJECT_BASE = {
  matematica: { teacher: "Ferretto", channel: "Professor Ferretto" },
  fisica: { teacher: "Professor Boaro", channel: "Professor Boaro" },
  quimica: { teacher: "Professor Igor Química", channel: "Professor Igor Química" },
  biologia: { teacher: "Paulo Jubilut", channel: "Biologia Total com Jubilut" },
  historia: { teacher: "Debora Aladim", channel: "Debora Aladim" },
  geografia: { teacher: "Parabolica", channel: "Parabolica" },
  portugues: { teacher: "Professor Noslen", channel: "Professor Noslen" },
  literatura: { teacher: "Professor Noslen", channel: "Professor Noslen" },
  redacao: { teacher: "Professor Noslen", channel: "Professor Noslen" },
  filosofia: { teacher: "Parabolica", channel: "Parabolica" },
  sociologia: { teacher: "Parabolica", channel: "Parabolica" },
  ingles: { teacher: "Carina Fragozo", channel: "English in Brazil" },
  espanhol: { teacher: "Nailla Malta", channel: "Estrategia Vestibulares" },
  "metodo-uerj": { teacher: "Estratégia UERJ", channel: "Seleção Aprova+" },
};

const SUBJECT_VIDEO_DEFAULTS = {
  matematica: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  fisica: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  quimica: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  biologia: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  historia: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  geografia: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  portugues: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  literatura: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  redacao: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  filosofia: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  sociologia: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  ingles: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
  espanhol: {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  },
};

const buildYouTubeUrls = (videoId) => ({
  youtubeUrl: `https://www.youtube.com/watch?v=${videoId}`,
  embedUrl: `https://www.youtube.com/embed/${videoId}`,
});

// Mapa central tópico -> ID do vídeo do YouTube.
// Chave = id da aula (`${subjectId}-${slug do tópico}`). Preencher aqui é o
// único lugar que precisa de manutenção quando entra um vídeo novo.
const LESSON_VIDEOS = {
  // fisica
  "fisica-dinamica": "8Odjs6gmMRA",
  "fisica-leis-de-newton": "SYqZrICH2NE",
  "fisica-trabalho-e-energia": "MhaGUBcAy-Y",
  "fisica-impulso-e-quantidade-de-movimento": "qXfu31IC8Q4",
  "fisica-gravitacao": "-8140NsksEg",
  "fisica-termologia": "QUvmXOY2WvI",
  "fisica-calorimetria": "ePwrxyCcqDg",
  "fisica-ondas": "0WeaGRPun94",
  "fisica-eletrodinamica": "46nINK2nsX8",
  "fisica-magnetismo": "AFACIE-UH6A",
  // quimica
  "quimica-estrutura-atomica": "MtBbVt7eInE",
  "quimica-tabela-periodica": "X9FLNt3bJ1k",
  "quimica-funcoes-inorganicas": "SFGUPgcsu3w",
  "quimica-reacoes-quimicas": "u7NSnN9UBB4",
  "quimica-estequiometria": "cAnsgi6v4fk",
  "quimica-solucoes": "KtiEiMBpso8",
  "quimica-termoquimica": "vqh99WJwRAs",
  "quimica-eletroquimica": "z5GziuQoUxk",
  "quimica-quimica-organica": "baNREGIK1V8",
  "quimica-funcoes-organicas": "97H9LuCX-pQ",
  "quimica-isomeria": "ayx-BhFZY0g",
  // biologia
  "biologia-citologia": "pibH054EN4M",
  "biologia-bioquimica-celular": "ii7b3cF7j4o",
  "biologia-organelas": "V_hAOq5iWvA",
  "biologia-metabolismo-energetico": "eIE8qLt5wMA",
  "biologia-genetica": "2rqEmRrtkYc",
  "biologia-biotecnologia": "VYC9v9E9-xQ",
  "biologia-evolucao": "4iP6cazPLII",
  "biologia-fisiologia-humana": "HuX4YySqRmg",
  "biologia-botanica": "nLRy7t8T0W4",
  "biologia-zoologia": "rLRAZ1Mzqsg",
  "biologia-microbiologia": "FjqksBI0Ic0",
  "biologia-imunologia": "KwJsEnIMPj0",
  // portugues
  "portugues-funcoes-da-linguagem": "xWprvm2ZqCM",
  "portugues-variacao-linguistica": "6fBOVygtNoU",
  "portugues-generos-textuais": "Ucjv4LT8CSg",
  "portugues-coesao-e-coerencia": "IIU6i3UXyi0",
  "portugues-figuras-de-linguagem": "n0e75nRstcU",
  "portugues-classes-gramaticais": "ohblr5iboO8",
  "portugues-sintaxe": "03MnId-DoJk",
  "portugues-pontuacao": "9tdpcfdr244",
  "portugues-concordancia": "4ZJnTqTk4_Y",
  "portugues-regencia": "B0EgJVneeGE",
  "portugues-crase": "yUpRa62vcSI",
  // historia
  "historia-historia-do-brasil-colonial": "I8sRO8QlN4c",
  "historia-independencia-do-brasil": "Fr9lurVLNyo",
  "historia-brasil-imperio": "2skEPARnorI",
  "historia-republica-velha": "FmGVa7W--mg",
  "historia-era-vargas": "jQU6Ojetq8M",
  "historia-ditadura-militar": "0A8fvJKzhcc",
  "historia-nova-republica": "ksyBneLcPe8",
  "historia-revolucao-industrial": "t6nJNv-pNr8",
  "historia-revolucao-francesa": "ppInSLfkRWo",
  "historia-primeira-guerra-mundial": "Xi8Vj7aDcvg",
  "historia-segunda-guerra-mundial": "75eeykQFbdU",
  "historia-guerra-fria": "eQ08AS5ZHQQ",
  "historia-globalizacao": "cuHddXfinDE",
  // geografia
  "geografia-cartografia": "6WPETLFx5tE",
  "geografia-clima": "7mkEkg3QozA",
  "geografia-relevo": "kOU5eNdtc4k",
  "geografia-hidrografia": "5IwzAlz9sH4",
  "geografia-vegetacao": "ZlB6MZmpKls",
  "geografia-urbanizacao": "HpaLKYnY3AQ",
  "geografia-industrializacao": "JhckdzGmfR8",
  "geografia-populacao": "jd_Pq49Zrm4",
  "geografia-geopolitica": "xZuZTgXfjoc",
  "geografia-globalizacao": "1JnFqa8bJps",
  "geografia-agricultura": "oPltd0jYUMU",
  "geografia-problemas-ambientais": "zOO16vcrptg",
  "geografia-energia": "rhYtEp6qInk",
  "geografia-transportes": "SX4uAj0WV0s",
  // literatura
  "literatura-escolas-literarias": "WGZFBePibF0",
  "literatura-quinhentismo": "WULOzFYZ30g",
  "literatura-barroco": "1FN2jCxgnt0",
  "literatura-arcadismo": "-ko2O_3gijM",
  "literatura-romantismo": "PyUy_9mKGCk",
  "literatura-realismo": "iCXp_ic4p_E",
  "literatura-naturalismo": "0ca0bBqnxE4",
  "literatura-parnasianismo": "JKmrUc1PhuE",
  "literatura-simbolismo": "rVjVUTXHocQ",
  "literatura-modernismo": "WmOICqpg4Rg",
  "literatura-literatura-contemporanea": "dWmGwQCl32s",
  // redacao
  "redacao-estrutura-da-redacao-enem": "CjUCTZstyK8",
  "redacao-introducao": "WfP2bl5xb5E",
  "redacao-desenvolvimento": "tDwcYr_-j0g",
  "redacao-conclusao": "LcTBcoKjk7U",
  "redacao-repertorio-sociocultural": "UcWul9zMlr4",
  "redacao-tese": "MeKHJVPNV30",
  "redacao-argumentacao": "IGmZHrihXN8",
  "redacao-proposta-de-intervencao": "EUv4aKg1UFk",
  "redacao-competencias-do-enem": "AMbFB_cFYek",
  "redacao-erros-comuns": "2ukOzhZhKrQ",
  "redacao-analise-de-redacoes-nota-1000": "tIK0-HrPyxY",
  // filosofia
  "filosofia-filosofia-antiga": "Zy7EwpV3qqI",
  "filosofia-socrates": "8cfp9vxE7Uw",
  "filosofia-platao": "GYISmIglyc8",
  "filosofia-aristoteles": "e90__VTudpo",
  "filosofia-filosofia-medieval": "ZG5IhFamFeo",
  "filosofia-filosofia-moderna": "bv9obMrnFyY",
  "filosofia-iluminismo": "mofK6eehDZw",
  "filosofia-etica": "92OBGFJg0lM",
  "filosofia-politica": "vVwckAou7LY",
  "filosofia-epistemologia": "Uk8XJz988Ac",
  // sociologia
  "sociologia-cultura": "1OGgnqkMLH8",
  "sociologia-sociedade": "ZdIrgqd7keI",
  "sociologia-trabalho": "LQPffshbEvE",
  "sociologia-cidadania": "7eXURxPO1Ls",
  "sociologia-movimentos-sociais": "N6FSOCflYMc",
  "sociologia-desigualdade-social": "m1mMyomcFdA",
  "sociologia-industria-cultural": "K6dwLSWL8sA",
  "sociologia-globalizacao": "5LM03AZxaQw",
  "sociologia-democracia": "GLC282sDZ6E",
  "sociologia-estado-e-poder": "UI67v44GQ6A",
  // ingles
  "ingles-interpretacao-de-texto": "jBkRAG8L12o",
  "ingles-cognatos": "kVUKDwPMwd0",
  "ingles-falsos-cognatos": "oTV4QDyZq5s",
  "ingles-tempos-verbais": "Jbl46pYR_bc",
  "ingles-pronomes": "ltDuWvJaUXU",
  "ingles-conectivos": "CC8lZiwe5Vs",
  "ingles-leitura-instrumental": "GN3baPvavIE",
  // espanhol
  "espanhol-interpretacao-de-texto": "fYBXOSTD1pI",
  "espanhol-falsos-cognatos": "iWpjj-lBYL4",
  "espanhol-tempos-verbais": "rgt0N_0WG8A",
  "espanhol-pronomes": "6qlHhfQmKf4",
  "espanhol-conectivos": "Djuv1gF0qp0",
  "espanhol-vocabulario": "9T9U8n-PC0o",
  "espanhol-leitura-instrumental": "3eV4KxLM-Zc",
  // Lacunas UERJ (Etapa 3) — obras do edital, redação, geografia RJ e método do Discursivo
  "literatura-ainda-estou-aqui": "TtuwD62r8_I",
  "literatura-o-cortico": "A9gSO0YZyWI",
  "literatura-o-bem-amado": "XSMxlAtPFHA",
  // "literatura-luanda-lisboa-paraiso": LACUNA — sem videoaula de vestibular boa (só resenha)
  "geografia-geografia-do-rio-de-janeiro": "DCOE9dh57Zs",
  "redacao-redacao-uerj": "QLD7UCJXJJ0",
  "metodo-uerj-como-funciona-o-exame-discursivo": "Fr_FVWpkfpY",
  "metodo-uerj-tecnica-de-resposta-discursiva": "RUml08cXowQ",
};

// Taxonomia de prova (substitui o antigo campo 'focus'): cada aula serve a uma
// ou mais provas. Regra central por matéria + exceções por tópico.
const PROVAS_ALL = ["enem", "uerj-qualificacao", "uerj-discursiva"];
const PROVAS_UERJ = ["uerj-qualificacao", "uerj-discursiva"];
const PROVAS_ENEM = ["enem"];
const PROVAS_QUALIF = ["uerj-qualificacao"];
const PROVAS_DISC = ["uerj-discursiva"];

const PROVAS_BY_SUBJECT = {
  matematica: PROVAS_ALL,
  fisica: PROVAS_ALL,
  quimica: PROVAS_ALL,
  biologia: PROVAS_ALL,
  historia: PROVAS_ALL,
  geografia: PROVAS_ALL,
  ingles: PROVAS_ALL,
  espanhol: PROVAS_ALL,
  portugues: PROVAS_ALL,
  literatura: PROVAS_ALL,
  // Filosofia, Sociologia e a redação modelo-ENEM caem só no ENEM.
  filosofia: PROVAS_ENEM,
  sociologia: PROVAS_ENEM,
  redacao: PROVAS_ENEM,
  // Categoria de método/estratégia: conteúdo do Discursivo da UERJ.
  "metodo-uerj": PROVAS_DISC,
};

// Exceções por aula (id = `${subjectId}-${slug do tópico}`):
// gramática normativa e escolas literárias de baixa incidência no ENEM = só UERJ.
const PROVAS_OVERRIDES = {
  "portugues-classes-gramaticais": PROVAS_UERJ,
  "portugues-sintaxe": PROVAS_UERJ,
  "portugues-concordancia": PROVAS_UERJ,
  "portugues-regencia": PROVAS_UERJ,
  "portugues-crase": PROVAS_UERJ,
  "literatura-quinhentismo": PROVAS_UERJ,
  "literatura-arcadismo": PROVAS_UERJ,
  "literatura-naturalismo": PROVAS_UERJ,
  "literatura-parnasianismo": PROVAS_UERJ,
  "literatura-simbolismo": PROVAS_UERJ,
  // Lacunas UERJ: obras do edital + recortes específicos da banca.
  "literatura-ainda-estou-aqui": PROVAS_QUALIF,
  "literatura-o-cortico": PROVAS_QUALIF,
  "literatura-luanda-lisboa-paraiso": PROVAS_DISC,
  "literatura-o-bem-amado": PROVAS_DISC,
  "geografia-geografia-do-rio-de-janeiro": PROVAS_UERJ,
  "redacao-redacao-uerj": PROVAS_DISC,
};

const computeProvas = (subjectId, lessonId) =>
  PROVAS_OVERRIDES[lessonId] ?? PROVAS_BY_SUBJECT[subjectId] ?? PROVAS_ENEM;

const withVideo = (subjectId, item) => {
  const base = SUBJECT_BASE[subjectId];
  const lessonId = item.id ?? `${subjectId}-${slugify(item.topic)}`;
  const mappedId = LESSON_VIDEOS[lessonId];
  const mapped = mappedId ? buildYouTubeUrls(mappedId) : null;
  const defaults = SUBJECT_VIDEO_DEFAULTS[subjectId] ?? {
    youtubeUrl: PLACEHOLDER_VIDEO_URL,
    embedUrl: PLACEHOLDER_EMBED_URL,
  };
  const youtubeUrl = item.youtubeUrl ?? mapped?.youtubeUrl ?? defaults.youtubeUrl;
  const embedUrl = item.embedUrl ?? mapped?.embedUrl ?? defaults.embedUrl;

  return {
    id: lessonId,
    subjectId,
    topic: item.topic,
    description: item.description,
    module: item.module ?? "",
    moduleDescription: item.moduleDescription ?? "",
    teacher: item.teacher ?? base.teacher,
    channel: item.channel ?? base.channel,
    level: item.level,
    priority: item.priority,
    provas: computeProvas(subjectId, lessonId),
    cicloEdital: item.cicloEdital ?? "",
    youtubeUrl,
    embedUrl,
    isPlaylist: embedUrl.includes("videoseries") || embedUrl.includes("listType=user_uploads"),
    isPlaceholder:
      youtubeUrl === PLACEHOLDER_VIDEO_URL ||
      embedUrl === PLACEHOLDER_EMBED_URL ||
      youtubeUrl.includes("VIDEO_URL_AQUI") ||
      embedUrl.includes("YOUTUBE_EMBED_URL_AQUI"),
  };
};

const buildSubjectLessons = (subjectId, lessons) => lessons.map((lesson) => withVideo(subjectId, lesson));

export const TRAIL_VIDEO_PLACEHOLDERS = {
  videoUrl: PLACEHOLDER_VIDEO_URL,
  embedUrl: PLACEHOLDER_EMBED_URL,
};

export const TRAIL_VIDEO_LIBRARY = [
  ...buildSubjectLessons("matematica", [
    {
      topic: "Sistema de numeração decimal",
      description: "Classes, ordens, valor posicional e leitura numerica para o aluno não tropeçar na base.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("Jf0sA3wBqXE"),
    },
    {
      topic: "Conjuntos numericos",
      description: "Naturais, inteiros e a ampliação dos conjuntos para organizar reta numerica, sinais e classificação.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("Y_mYgLkuEl4"),
    },
    {
      topic: "Soma e subtração com inteiros e decimais",
      description: "Adição, subtração e leitura de sinais em números inteiros e decimais para consolidar a base aritmética.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("e78_5WIssSU"),
    },
    {
      topic: "Expressões numericas",
      description: "Ordem das operações, uso de parenteses e resolução organizada sem pular etapa.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("BhDm2qGy780"),
    },
    {
      topic: "Frações e números racionais",
      description: "Leitura de frações, forma racional e conexao com divisão, comparação e escrita numerica.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("NYAeWhz53NM"),
    },
    {
      topic: "Potenciação",
      description: "Definição, propriedades e leitura de potências para sustentar algebra, ciência e notação.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("4Vfw1XiHTpM"),
    },
    {
      topic: "Radiciação",
      description: "Raizes, simplificação e propriedades para preparar o terreno de irracionais e algebra.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("QmIjZgKhAEo"),
    },
    {
      topic: "Razao e proporção",
      description: "Comparação de grandezas, escalas e relações que aparecem muito em problemas contextualizados.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("JXx9RCzfgCw"),
    },
    {
      topic: "Porcentagem",
      description: "Aumentos, descontos, variação percentual e leitura de tabelas com aplicação direta em prova.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("CERiIwParX4"),
    },
    {
      topic: "Regra de três",
      description: "Proporções diretas e inversas para problemas de consumo, produção, escalas e grandezas.",
      module: "Matemática básica",
      moduleDescription: "Base numerica, soma, subtração, frações, expressões, potência e proporção para destravar toda a trilha de exatas.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("alLifth7gxE"),
    },
    {
      topic: "Funções",
      description: "Conceito geral de função, dominio, imagem e leitura gráfica como base para a algebra.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("SPZqQ5qn3P0"),
    },
    {
      topic: "Função afim",
      description: "Coeficientes, reta, taxa de variação e interpretação de gráficos lineares.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("hdMFlAv5GkU"),
    },
    {
      topic: "Função quadrática",
      description: "Parabola, vertices, zeros e problemas envolvendo máximos e mínimos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("ZpW9Xb5iyt4"),
    },
    {
      topic: "Exponencial",
      description: "Crescimento e decaimento exponencial em contextos de população, juros e ciências.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("gMGz-dB9few"),
    },
    {
      topic: "Logaritmo",
      description: "Definição, propriedades e leitura de problemas de escala e simplificação de expressões.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("k2XkYEUH9nA"),
    },
    {
      topic: "PA e PG",
      description: "Sequências, termos gerais e somas em progressão com leitura aplicada.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("waIXJzREyw8"),
    },
    {
      topic: "Geometria plana",
      description: "Poligonos, triangulos, áreas e semelhanca, com alta recorrência em problemas visuais.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("0CnUdzmpO8E"),
    },
    {
      topic: "Geometria espacial",
      description: "Prismas, cilindros, cones e volumes em contextualização de embalagens e objetos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("yXYooR_QZ3Y"),
    },
    {
      topic: "Trigonometria",
      description: "Razões trigonometrica, circulo e leitura de triangulos em problemas de angulos e medidas.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("4sTUs4ll3dI"),
    },
    {
      topic: "Probabilidade",
      description: "Eventos, casos favoráveis e leitura lógica de situações com risco e aleatoriedade.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("FwQ-fjrQXac"),
    },
    {
      topic: "Estatística",
      description: "Média, mediana, moda, desvio e interpretação de gráficos e tabelas.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("mSk2vjGXA90"),
    },
    {
      topic: "Analise combinatoria",
      description: "Principio multiplicativo, arranjos e combinações em contagem estruturada.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("rSgs9YD9ns0"),
    },
    {
      topic: "Matemática financeira",
      description: "Juros simples e compostos, descontos e leitura de parcelamentos com muita cara de ENEM.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("N27xZJj1m-4"),
    },
  ]),
  ...buildSubjectLessons("fisica", [
    {
      topic: "Cinemática",
      description: "Movimento uniforme e variado, gráficos e leitura de trajetorias no tempo.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("0qLf8ivEDV4"),
    },
    {
      topic: "Dinamica",
      description: "Forcas, interações e estrutura dos problemas mecanicos mais cobrados.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Leis de Newton",
      description: "Aplicação das leis ao cotidiano, diagramas de forca e analise de equilibrio.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Trabalho e energia",
      description: "Energia cinética, potencial e conservação em problemas diretos e contextualizados.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Impulso e quantidade de movimento",
      description: "Choques, variação de movimento e interpretação de sistemas em interação.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Gravitação",
      description: "Leis da gravitação, orbitas e leitura de situações astronomicas e de campo gravitacional.",
      level: "Avançado",
      priority: "Baixa",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Hidrostática",
      description: "Pressão, densidade, empuxo e fluídos em equilibrio com aplicação direta em prova.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("pQlCv40jTCc"),
    },
    {
      topic: "Termologia",
      description: "Temperatura, dilatação e comportamentos termicos em materiais e fenômenos do dia a dia.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Calorimetria",
      description: "Trocas de calor, capacidade termica e equilibrio em sistemas simples.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Optica",
      description: "Reflexao, refração, lentes e espelhos em leitura de imagem e instrumentos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("gvUfJXHybIY"),
    },
    {
      topic: "Ondas",
      description: "Conceitos de onda, frequência, comprimento e fenômenos ondulatórios.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Eletrostática",
      description: "Cargas, interações eletricas e campo eletrico em situações fundamentais.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("6o3zDgWmBKw"),
    },
    {
      topic: "Eletrodinamica",
      description: "Corrente, resistores, associações e potência eletrica em circuitos básicos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Magnetismo",
      description: "Campo magnético, forca magnética e noção eletromagnética aplicada.",
      level: "Avançado",
      priority: "Baixa",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("quimica", [
    {
      topic: "Estrutura atomica",
      description: "Modelos atomicos, particulas fundamentais e noção de configuração eletronica.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Tabela periodica",
      description: "Familias, períodos e propriedades periodicas para leitura química rapida.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Ligações químicas",
      description: "Ionica, covalente e metalica com foco em propriedades e comparações.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("UjXlHX3EEi0"),
    },
    {
      topic: "Funções inorganicas",
      description: "Acidos, bases, sais e oxidos com identificação, nomenclatura e aplicação.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Reações químicas",
      description: "Tipos de reação e leitura de transformações em processos naturais e industriais.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Estequiometria",
      description: "Proporções em reações, balanceamento e calculos classicos de massa e mol.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Soluções",
      description: "Concentração, diluição e mistura com leitura aplicada em problemas.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Termoquímica",
      description: "Entalpia, reações endotermicas e exotermicas e energia envolvida em processos.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Cinética química",
      description: "Velocidade de reação, fatores de influência e leitura de processos dinamicos.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("ltJRR5v6l-g"),
    },
    {
      topic: "Equilibrio químico",
      description: "Equilibrio em sistemas reversíveis e principio de Le Chatelier.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("Qw7GDxqcX6o"),
    },
    {
      topic: "Eletroquímica",
      description: "Pilhas, eletrólise e transferência de eletrons em sistemas químicos.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Química organica",
      description: "Introdução ao carbono, cadeias e principios da estrutura organica.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Funções organicas",
      description: "Identificação de grupos funcionais e leitura de compostos importantes.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Isomeria",
      description: "Isomeria plana e espacial com comparação estrutural e propriedades.",
      level: "Avançado",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("biologia", [
    {
      topic: "Citologia",
      description: "Conceitos celulares essenciais, tipos de celula e organização estrutural.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Bioquímica celular",
      description: "Agua, sais, carboidratos, lipideos, proteinas e acidos nucleicos.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Organelas",
      description: "Funções das organelas e relação com metabolismo, sintese e transporte.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Metabolismo energético",
      description: "Respiração, fermentação e fotossintese para compreender produção de energia.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Genética",
      description: "Leis básicas, heredogramas e interpretação de cruzamentos e heranca.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Biotecnologia",
      description: "DNA recombinante, transgenicos, clonagem e aplicações contemporaneas.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Evolução",
      description: "Teorias evolutivas, seleção natural e mecanismos de variabilidade.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Ecologia",
      description: "Cadeias, ciclos, impactos ambientais e relações ecológicas com muita cara de ENEM.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("XvdePktAui8"),
    },
    {
      topic: "Fisiologia humana",
      description: "Sistemas do corpo, integração funcional e leitura de fenômenos biológicos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Botanica",
      description: "Grupos vegetais, estruturas e fisiologia básica das plantas.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Zoologia",
      description: "Principais grupos animais, características e comparações estruturais.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Microbiologia",
      description: "Virus, bacterias, fungos e protozoários em contexto de saude e ambiente.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Imunologia",
      description: "Defesa do organismo, anticorpos, vacinas e resposta imune.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("historia", [
    {
      topic: "História do Brasil colonial",
      description: "Colonização, economia, escravidao e estruturas do Brasil colonial.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Independência do Brasil",
      description: "Crise do sistema colonial e processos políticos da independência.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Brasil Imperio",
      description: "Primeiro e Segundo Reinado, conflitos e transformações do século XIX.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Republica Velha",
      description: "Oligarquias, coronelismo, cafe e movimentos sociais no inicio republicano.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Era Vargas",
      description: "Centralização do poder, trabalhismo e modernização autoritária.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Ditadura Militar",
      description: "Golpe de 1964, AI-5, resistência e abertura política.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Nova Republica",
      description: "Redemocratização, Constituição de 1988 e transformações recentes.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Revolução Industrial",
      description: "Origem do capitalismo industrial e impactos sociais e urbanos.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Revolução Francesa",
      description: "Crise do Antigo Regime, iluminismo e reorganização política moderna.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Primeira Guerra Mundial",
      description: "Imperialismo, alianças e reconfiguração geopolítica do inicio do século XX.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Segunda Guerra Mundial",
      description: "Nazifascismo, conflito global e impactos políticos e humanos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Guerra Fria",
      description: "Bipolaridade, disputas ideológicas e conflitos indiretos entre blocos.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Globalização",
      description: "Transformações economicas, culturais e políticas do mundo contemporaneo.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("geografia", [
    {
      topic: "Cartografia",
      description: "Escala, coordenadas, projeções e leitura de mapas para ENEM e UERJ.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Clima",
      description: "Elementos climáticos, massas de ar e interpretação de mapas e gráficos.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Relevo",
      description: "Formas de relevo, agentes modeladores e leitura geomorfológica.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Hidrografia",
      description: "Bacias, usos da agua e conflitos hidricos em contexto geográfico.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Vegetação",
      description: "Biomas, formações vegetais e relação com clima e ocupação humana.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Urbanização",
      description: "Metropolização, segregação e problemas urbanos com leitura social do espaco.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Industrialização",
      description: "Etapas, desconcentração e organização espacial da industria.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "População",
      description: "Demografia, indicadores e dinamicas migratorias com leitura de dados.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Geopolítica",
      description: "Conflitos, territórios e relações de poder no espaco mundial.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Globalização",
      description: "Fluxos, redes, comercio e desigualdades no mundo globalizado.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Agricultura",
      description: "Modelos agrários, modernização e impactos no campo brasileiro e mundial.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Problemas ambientais",
      description: "Poluição, desmatamento, clima e sustentabilidade com alta aderência ao ENEM.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Energia",
      description: "Matriz energética, fontes renováveis e impactos geopolíticos e ambientais.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Transportes",
      description: "Logística, modal, circulação e integração territorial.",
      level: "Básico",
      priority: "Baixa",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Geografia do Rio de Janeiro",
      description: "Urbanização da Região Metropolitana, conflitos socioambientais, economia fluminense e leitura de mapas do RJ — recorte forte da banca da UERJ.",
      level: "Intermediário",
      priority: "Alta",
    },
  ]),
  ...buildSubjectLessons("portugues", [
    {
      topic: "Interpretação de texto",
      description: "Leitura global, inferência, sentido e estrategia central para ENEM e UERJ.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
      ...buildYouTubeUrls("XsN0e_xPyNI"),
    },
    {
      topic: "Funções da linguagem",
      description: "Reconhecer intenção comunicativa e efeito de sentido em textos diversos.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Variação linguística",
      description: "Norma, uso, registros e leitura crítica de linguagem em contexto.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Gêneros textuais",
      description: "Características e função social dos gêneros mais frequentes em prova.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Coesão e coerência",
      description: "Progressão textual, conectivos e articulação de ideias.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Figuras de linguagem",
      description: "Efeitos expressivos, interpretação e uso em leitura de poesia e publicidade.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Classes gramaticais",
      description: "Revisão funcional das classes com aplicação em sentido e estrutura.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Sintaxe",
      description: "Termos da oração, período e relações estruturais em construções recorrentes.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Pontuação",
      description: "Uso expressivo e estrutural da pontuação na interpretação e na norma.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Concordância",
      description: "Concordância nominal e verbal em leitura e correção de enunciados.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Regência",
      description: "Regência verbal e nominal com foco em construção padrao e interpretação.",
      level: "Avançado",
      priority: "Média",
      focus: "UERJ",
    },
    {
      topic: "Crase",
      description: "Uso do acento grave em contextos práticos e muito cobrados.",
      level: "Intermediário",
      priority: "Média",
      focus: "UERJ",
    },
  ]),
  ...buildSubjectLessons("literatura", [
    {
      topic: "Escolas literárias",
      description: "Panorama geral para localizar movimentos, autores e estilos.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Quinhentismo",
      description: "Textos iniciais do Brasil e contexto das cronicas e cartas de viagem.",
      level: "Básico",
      priority: "Baixa",
      focus: "UERJ",
    },
    {
      topic: "Barroco",
      description: "Contrastes, religiosidade e linguagem rebuscada no contexto colonial.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Arcadismo",
      description: "Equilibrio formal, bucolismo e reação ao exagero barroco.",
      level: "Básico",
      priority: "Baixa",
      focus: "UERJ",
    },
    {
      topic: "Romantismo",
      description: "Nacionalismo, idealização e gerações romanticas na literatura brasileira.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Realismo",
      description: "Ironia, crítica social e analise psicológica com forte presença em prova.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Naturalismo",
      description: "Determinismo, cientificismo e representação crua da sociedade.",
      level: "Intermediário",
      priority: "Média",
      focus: "UERJ",
    },
    {
      topic: "Parnasianismo",
      description: "Formalismo, objetividade e leitura da poesia mais descritiva.",
      level: "Intermediário",
      priority: "Baixa",
      focus: "UERJ",
    },
    {
      topic: "Simbolismo",
      description: "Subjetividade, musicalidade e sugestão como marcas centrais.",
      level: "Intermediário",
      priority: "Baixa",
      focus: "UERJ",
    },
    {
      topic: "Modernismo",
      description: "Ruptura estética, linguagens modernas e autores fundamentais do século XX.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Literatura contemporanea",
      description: "Tendências mais recentes e leitura de linguagem, forma e contexto.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Ainda estou aqui",
      description: "Marcelo Rubens Paiva. Obra do 1º Exame de Qualificação (UERJ 2027): memória, ditadura e ausência. Foco em temas, narrador e contexto histórico.",
      module: "Obras Literárias UERJ",
      moduleDescription: "Análise das obras obrigatórias do ciclo vigente, no recorte que a UERJ cobra: estilo, contexto histórico-literário e questão-tipo da banca.",
      cicloEdital: "2027",
      level: "Intermediário",
      priority: "Alta",
    },
    {
      topic: "O Cortiço",
      description: "Aluísio Azevedo. Obra do 2º Exame de Qualificação (UERJ 2027): marco do Naturalismo, determinismo, personagem coletivo e crítica social.",
      module: "Obras Literárias UERJ",
      cicloEdital: "2027",
      level: "Intermediário",
      priority: "Alta",
    },
    {
      topic: "Luanda, Lisboa, Paraíso",
      description: "Djaimilia Pereira de Almeida. Obra da prova de Língua Portuguesa e Literaturas (Discursivo UERJ 2027): literatura contemporânea de língua portuguesa, diáspora e identidade.",
      module: "Obras Literárias UERJ",
      cicloEdital: "2027",
      level: "Avançado",
      priority: "Alta",
    },
    {
      topic: "O bem-amado",
      description: "Dias Gomes. Obra-tema da Redação do Discursivo (UERJ 2027): sátira política e coronelismo. Base argumentativa para a redação — não para resumir.",
      module: "Obras Literárias UERJ",
      cicloEdital: "2027",
      level: "Intermediário",
      priority: "Alta",
    },
  ]),
  ...buildSubjectLessons("redacao", [
    {
      topic: "Estrutura da redação ENEM",
      description: "Visão global do texto dissertativo-argumentativo e da organização exigida.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM",
    },
    {
      topic: "Introdução",
      description: "Abertura de texto com tema, recorte e tese de modo claro e estrategico.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Desenvolvimento",
      description: "Como construir paragrafos fortes com argumento, repertório e comentário.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Conclusão",
      description: "Fechamento funcional com retomada de tese e desfecho coerente.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Repertório sociocultural",
      description: "Escolher e usar repertório com pertinência, produtividade e naturalidade.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Tese",
      description: "Posicionamento claro e sustentável para orientar todo o texto.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Argumentação",
      description: "Encadeamento lógico das ideias com aprofundamento e prova textual.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Proposta de intervenção",
      description: "Agente, ação, meio, finalidade e detalhamento para a competência 5.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM",
    },
    {
      topic: "Competências do ENEM",
      description: "Leitura das cinco competências e o que cada uma exige na avaliação.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM",
    },
    {
      topic: "Erros comuns",
      description: "Os desvios que mais derrubam nota em estrutura, linguagem e argumentação.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Analise de redações nota 1000",
      description: "Ler textos fortes com criterio para modelar repertório e decisão de escrita.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Redação UERJ",
      description: "A redação do Discursivo não é a do ENEM: dissertativo-argumentativa amarrada à obra indicada, 20–30 linhas, sem proposta de intervenção. Tese + diálogo com o livro, sem resumir.",
      level: "Intermediário",
      priority: "Alta",
    },
  ]),
  ...buildSubjectLessons("filosofia", [
    {
      topic: "Filosofia antiga",
      description: "Nascimento da filosofia, visão de mundo grega e fundamentos classicos.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Socrates",
      description: "Maiêutica, ética e o metodo socrático na formação do pensamento ocidental.",
      level: "Básico",
      priority: "Baixa",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Platão",
      description: "Mundo das ideias, política e conhecimento em um dos autores mais cobrados.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Aristoteles",
      description: "Lógica, ética e política com leitura sistemática do real.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Filosofia medieval",
      description: "Relação entre fe e razao em Agostinho e Tomas de Aquino.",
      level: "Intermediário",
      priority: "Baixa",
      focus: "UERJ",
    },
    {
      topic: "Filosofia moderna",
      description: "Racionalismo, empirismo e mudancas na noção de sujeito e conhecimento.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Iluminismo",
      description: "Razao, crítica ao absolutismo e pensamento político moderno.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Ética",
      description: "Problemas morais, valores e dilemas com aplicação direta em questões interpretativas.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Política",
      description: "Estado, poder, democracia e organização da vida coletiva.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Epistemologia",
      description: "Como o conhecimento se constitui e quais são seus limites.",
      level: "Avançado",
      priority: "Baixa",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("sociologia", [
    {
      topic: "Cultura",
      description: "Conceitos de cultura, identidade e diversidade no pensamento sociológico.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Sociedade",
      description: "Estruturas sociais, interações e formas de organização coletiva.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Trabalho",
      description: "Mudancas no mundo do trabalho, alienação e organização produtiva.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Cidadania",
      description: "Direitos, participação social e construção de pertencimento político.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Movimentos sociais",
      description: "Formação, reivindicação e papel político dos coletivos sociais.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Desigualdade social",
      description: "Renda, classe, mobilidade e leitura crítica da estrutura brasileira.",
      level: "Intermediário",
      priority: "Alta",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Industria cultural",
      description: "Midia, consumo e padronização cultural com leitura contemporanea.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Globalização",
      description: "Fluxos globais, cultura, trabalho e desigualdades no capitalismo recente.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Democracia",
      description: "Representação, participação e desafios democráticos atuais.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
    {
      topic: "Estado e poder",
      description: "Legitimidade, coerção e organização política da sociedade.",
      level: "Intermediário",
      priority: "Média",
      focus: "ENEM + UERJ",
    },
  ]),
  ...buildSubjectLessons("ingles", [
    {
      topic: "Interpretação de texto",
      description: "Leitura de anuncios, artigos, tirinhas e textos com inferência de sentido.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM",
    },
    {
      topic: "Cognatos",
      description: "Reconhecimento de vocabulário transparente para ganhar velocidade de leitura.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Falsos cognatos",
      description: "Palavras enganosas que exigem atenção para não comprometer a interpretação.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Tempos verbais",
      description: "Leitura funcional dos tempos verbais mais comuns em textos de prova.",
      level: "Intermediário",
      priority: "Baixa",
      focus: "ENEM",
    },
    {
      topic: "Pronomes",
      description: "Referência pronominal e coesão para compreender quem faz o que no texto.",
      level: "Básico",
      priority: "Baixa",
      focus: "ENEM",
    },
    {
      topic: "Conectivos",
      description: "Palavras-chave de oposição, causa, adição e conclusão na leitura instrumental.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Leitura instrumental",
      description: "Estrategias de skimming, scanning e leitura orientada por comando.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM",
    },
  ]),
  ...buildSubjectLessons("espanhol", [
    {
      topic: "Interpretação de texto",
      description: "Leitura de noticias, campanhas e tirinhas em espanhol com foco em sentido.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM",
    },
    {
      topic: "Falsos cognatos",
      description: "Palavras que parecem português, mas pedem leitura cuidadosa.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Tempos verbais",
      description: "Leitura funcional dos verbos mais recorrentes em texto instrumental.",
      level: "Intermediário",
      priority: "Baixa",
      focus: "ENEM",
    },
    {
      topic: "Pronomes",
      description: "Referência e coesão em estruturas simples e bastante recorrentes.",
      level: "Básico",
      priority: "Baixa",
      focus: "ENEM",
    },
    {
      topic: "Conectivos",
      description: "Marcadores de oposição, causa, adição e conclusão para leitura mais segura.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Vocabulário",
      description: "Campos lexicais recorrentes em temas sociais, culturais e cotidianos.",
      level: "Básico",
      priority: "Média",
      focus: "ENEM",
    },
    {
      topic: "Leitura instrumental",
      description: "Como resolver texto em espanhol sem depender de tradução linha a linha.",
      level: "Básico",
      priority: "Alta",
      focus: "ENEM",
    },
  ]),
  ...buildSubjectLessons("metodo-uerj", [
    {
      topic: "Como funciona o Exame Discursivo",
      description: "O mapa da 2ª fase antes de estudar conteúdo: redação obrigatória + 2 disciplinas específicas do curso, correção por critério, pesos e duração.",
      level: "Básico",
      priority: "Alta",
    },
    {
      topic: "Técnica de resposta discursiva",
      description: "Como pontuar de verdade: responder exatamente o comando, mostrar o raciocínio/cálculo, usar vocabulário técnico e organizar a resposta. Os erros que mais tiram ponto.",
      level: "Intermediário",
      priority: "Alta",
    },
  ]),
];
